### ISSUE TITLE
about Mesh-candidate BestFit algorithm

### ISSUE THREAD

**Issue by cuongdxk57** [opendatalab/DocLayout-YOLO#11]
Thank you for the your work . Could you provide the source code for the Mesh-candidate BestFit algorithm? Thank you very much!

**Comment by JulioZhao97** [comment]
Thanks for your interest in our work! We are currently planning to release code for Mesh-candidate BestFit, please keep focus on our project.

**Comment by JulioZhao97** [comment]
@cuongdxk57 Hello, the Mesh-candidate BestFit is available now.

**Comment by cuongdxk57** [comment]
> @cuongdxk57 Hello, the Mesh-candidate BestFit is available now.

thank you very much
