### ISSUE TITLE
数据集获取

### ISSUE THREAD

**Issue by njustczr** [opendatalab/DocLayout-YOLO#12]
hello,我在哪里能下载DocSynth300K  数据集呢？

**Comment by JulioZhao97** [comment]
您好，由于数据集较大正在上传，预计这周更新上去，请继续关注反馈，谢谢

**Comment by JulioZhao97** [comment]
@njustczr Hello, the dataset is available in https://huggingface.co/datasets/juliozhao/DocSynth300K
