### ISSUE TITLE
非常好的工作，有更为详细训练微调的说明文档吗？

### ISSUE THREAD

**Issue by Lucky-BenXie** [opendatalab/DocLayout-YOLO#17]

**Comment by JulioZhao97** [comment]
您好，目前有在公开数据集上的训练微调文档，相关数据准备、训练测试设置都在command里面可以找到：https://github.com/opendatalab/DocLayout-YOLO/blob/main/README.md#training-and-evaluation-on-public-dla-datasets
如果有别的问题欢迎指出反馈
