### ISSUE TITLE
Page detection

### ISSUE THREAD

**Issue by zdposter** [opendatalab/DocLayout-YOLO#21]
I have scanned documents, pictures of document taken by phone etc. where first I need to detect single page to eliminate rest of image or fix rotation. Is it possible to extend a model by such a feature?

Here are some example mages:
![handwritten_records](https://github.com/user-attachments/assets/bcc37ec2-1b77-4121-9642-d5ae33871656)
![binding-example 45](https://github.com/user-attachments/assets/8e2fb2c9-5d11-4298-92f0-e92542ece04a)
![book2](https://github.com/user-attachments/assets/7558ed52-11e0-454e-9d3a-d92fa2018512)

**Comment by JulioZhao97** [comment]
Hello! Thanks for you interest of utilizing our work! Could you please re-upload some example images? I cannot download images above.

**Comment by zdposter** [comment]
I put them to zip file [page_detection.zip](https://github.com/user-attachments/files/17537820/page_detection.zip)

**Comment by JulioZhao97** [comment]
![image](https://github.com/user-attachments/assets/a5d723a0-adeb-4f37-9974-93ebcce0b456)
![image](https://github.com/user-attachments/assets/124d0374-d5e6-4083-a07f-526003260290)
![image](https://github.com/user-attachments/assets/35647611-3092-4c8f-8e6d-9f19483b1039)

I have tested your provided examples and have follow suggestions:
1. For extract page and eliminate rest of image, DocLayout-YOLO can't deal with some unseen and complex writing styles (like the 3rd image)
2. For fix rotation, you may need to train a ODD (for rotated object detection) model with rotated boxes. For example, you can construct some rotated data on public dataset like DocLayNet, and train a ODD model using YOLOv8.
