### ISSUE TITLE
Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1,

### ISSUE THREAD

**Issue by whale1008** [opendatalab/DocLayout-YOLO#22]
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.

When I ran the code for the second time, the above situation occurred. How should I check and deal with this problem? Thank you.

**Comment by JulioZhao97** [comment]
> [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. [E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down. [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> 
> When I ran the code for the second time, the above situation occurred. How should I check and deal with this problem? Thank you.

Could you please provide a more detailed command and output information? Thank you!

**Comment by whale1008** [comment]
@JulioZhao97 The problem looks similar to this one： https://github.com/ultralytics/ultralytics/issues/15683，But the machine can be trained with ultralytics normally
command 
python train.py --data ./data_test --model m-doclayout --epoch 500 --image-size 1120 --batch-size 32 --project test --plot 1 --optimizer SGD --lr0 0.02 --pretrain ./doclayout_yolo_docsynth300k_imgsz1600.pt --device 0,1,2,3

**Comment by JulioZhao97** [comment]
I am not sure whether this is the case, could you please check:
1. Can single GPU training can perform normally?
2. Does the process truly stuck during some processes like dataloading or downloading? More detailed output is appreciated!

**Comment by whale1008** [comment]
@JulioZhao97  I adjusted the nccl waiting time to 10 minutes, and the log was the same as before.
```
Ultralytics YOLOv0.0.2 🚀 Python-3.10.13 torch-2.1.0+cu118 CUDA:0 (NVIDIA A100 80GB PCIe, 80995MiB)
                                                           CUDA:1 (NVIDIA A100 80GB PCIe, 80995MiB)
Overriding model.yaml nc=74 with nc=11
Transferred 1039/1051 items from pretrained weights
DDP: debug command /opt/conda/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 40177 /home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv0.0.2 🚀 Python-3.10.13 torch-2.1.0+cu118 CUDA:0 (NVIDIA A100 80GB PCIe, 80995MiB)
                                                           CUDA:1 (NVIDIA A100 80GB PCIe, 80995MiB)
TensorBoard: Start with 'tensorboard --logdir doclayout/11cls_doclayout-yolo_from_docsynth300k', view at http://localhost:6006/
Overriding model.yaml nc=74 with nc=11
Transferred 1039/1051 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/home/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
[E ProcessGroupNCCL.cpp:474] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600001 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:540] [Rank 0] Work WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) timed out in blocking wait (NCCL_BLOCKING_WAIT=1).
[E ProcessGroupNCCL.cpp:474] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:540] [Rank 1] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) timed out in blocking wait (NCCL_BLOCKING_WAIT=1).
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
Traceback (most recent call last):
  File "/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py", line 12, in <module>
    results = trainer.train()
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 214, in train
    self._do_train(world_size)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 333, in _do_train
    self._setup_train(world_size)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 276, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1914, in broadcast
    work.wait()
RuntimeError: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
Traceback (most recent call last):
  File "/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py", line 12, in <module>
    results = trainer.train()
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 214, in train
    self._do_train(world_size)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 333, in _do_train
    self._setup_train(world_size)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 273, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/utils/checks.py", line 653, in check_amp
    assert amp_allclose(YOLO("yolov8n.pt"), im)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/models/yolo/model.py", line 28, in __init__
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 144, in __init__
    self._load(model, task=task)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 233, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 807, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 733, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/base.py", line 17, in <module>
    from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/utils.py", line 19, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 12, in <module>
    from ultralytics.nn.modules import (
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/modules/__init__.py", line 20, in <module>
    from .block import (
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 8, in <module>
    from ultralytics.utils.torch_utils import fuse_conv_and_bn
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 1271, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 1197, in __init__
    with torch_distributed_zero_first(RANK):
  File "/opt/conda/envs/yolo/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 64, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3703, in barrier
    work.wait()
RuntimeError: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600001 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[2024-10-28 12:17:21,058] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2142) of binary: /opt/conda/envs/yolo/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/yolo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/yolo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-28_12:17:21
  host      : test-0
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2143)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-28_12:17:21
  host      : test-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2142)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/codes/DocLayout-YOLO/train.py", line 71, in <module>
    results = model.train(
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 660, in train
    self.trainer.train()
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 209, in train
    raise e
  File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 207, in train
    subprocess.run(cmd, check=True)
  File "/opt/conda/envs/yolo/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/conda/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '40177', '/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py']' returned non-zero exit status 1.
```

**Comment by whale1008** [comment]
@JulioZhao97 

> @JulioZhao97 I'm glad to hear from you. I adjusted the nccl waiting time to 10 minutes, and the log was the same as before.
> 
> ```
> Ultralytics YOLOv0.0.2 🚀 Python-3.10.13 torch-2.1.0+cu118 CUDA:0 (NVIDIA A100 80GB PCIe, 80995MiB)
>                                                            CUDA:1 (NVIDIA A100 80GB PCIe, 80995MiB)
> Overriding model.yaml nc=74 with nc=11
> Transferred 1039/1051 items from pretrained weights
> DDP: debug command /opt/conda/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 40177 /home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py
> WARNING:__main__:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> Ultralytics YOLOv0.0.2 🚀 Python-3.10.13 torch-2.1.0+cu118 CUDA:0 (NVIDIA A100 80GB PCIe, 80995MiB)
>                                                            CUDA:1 (NVIDIA A100 80GB PCIe, 80995MiB)
> TensorBoard: Start with 'tensorboard --logdir doclayout/11cls_doclayout-yolo_from_docsynth300k', view at http://localhost:6006/
> Overriding model.yaml nc=74 with nc=11
> Transferred 1039/1051 items from pretrained weights
> Freezing layer 'model.23.dfl.conv.weight'
> AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
> Creating new Ultralytics Settings v0.0.6 file ✅ 
> View Ultralytics Settings with 'yolo settings' or at '/home/.config/Ultralytics/settings.json'
> Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
> libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
> libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
> [E ProcessGroupNCCL.cpp:474] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600001 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:540] [Rank 0] Work WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) timed out in blocking wait (NCCL_BLOCKING_WAIT=1).
> [E ProcessGroupNCCL.cpp:474] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:540] [Rank 1] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) timed out in blocking wait (NCCL_BLOCKING_WAIT=1).
> [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
> Traceback (most recent call last):
>   File "/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py", line 12, in <module>
>     results = trainer.train()
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 214, in train
>     self._do_train(world_size)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 333, in _do_train
>     self._setup_train(world_size)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 276, in _setup_train
>     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1914, in broadcast
>     work.wait()
> RuntimeError: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
> Traceback (most recent call last):
>   File "/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py", line 12, in <module>
>     results = trainer.train()
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 214, in train
>     self._do_train(world_size)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 333, in _do_train
>     self._setup_train(world_size)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 273, in _setup_train
>     self.amp = torch.tensor(check_amp(self.model), device=self.device)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/utils/checks.py", line 653, in check_amp
>     assert amp_allclose(YOLO("yolov8n.pt"), im)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/models/yolo/model.py", line 28, in __init__
> [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
>     super().__init__(model=model, task=task, verbose=verbose)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 144, in __init__
>     self._load(model, task=task)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 233, in _load
>     self.model, self.ckpt = attempt_load_one_weight(weights)
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 807, in attempt_load_one_weight
>     ckpt, weight = torch_safe_load(weight)  # load ckpt
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 733, in torch_safe_load
>     ckpt = torch.load(file, map_location="cpu")
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1014, in load
>     return _load(opened_zipfile,
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1422, in _load
>     result = unpickler.load()
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 1415, in find_class
>     return super().find_class(mod_name, name)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/__init__.py", line 10, in <module>
>     from ultralytics.data.explorer.explorer import Explorer
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
>     from .base import BaseDataset
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/base.py", line 17, in <module>
>     from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/data/utils.py", line 19, in <module>
>     from ultralytics.nn.autobackend import check_class_names
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/__init__.py", line 3, in <module>
>     from .tasks import (
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 12, in <module>
>     from ultralytics.nn.modules import (
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/modules/__init__.py", line 20, in <module>
>     from .block import (
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 8, in <module>
>     from ultralytics.utils.torch_utils import fuse_conv_and_bn
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 1271, in <module>
>     SETTINGS = SettingsManager()  # initialize settings
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 1197, in __init__
>     with torch_distributed_zero_first(RANK):
>   File "/opt/conda/envs/yolo/lib/python3.10/contextlib.py", line 142, in __exit__
>     next(self.gen)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 64, in torch_distributed_zero_first
>     dist.barrier(device_ids=[local_rank])
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3703, in barrier
>     work.wait()
> RuntimeError: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600001 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [2024-10-28 12:17:21,058] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2142) of binary: /opt/conda/envs/yolo/bin/python
> Traceback (most recent call last):
>   File "/opt/conda/envs/yolo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/conda/envs/yolo/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
>     main()
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
>     run(args)
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
>     elastic_launch(
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/opt/conda/envs/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> /home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2024-10-28_12:17:21
>   host      : test-0
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 2143)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-10-28_12:17:21
>   host      : test-0
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 2142)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> Traceback (most recent call last):
>   File "/home/codes/DocLayout-YOLO/train.py", line 71, in <module>
>     results = model.train(
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 660, in train
>     self.trainer.train()
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 209, in train
>     raise e
>   File "/home/codes/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 207, in train
>     subprocess.run(cmd, check=True)
>   File "/opt/conda/envs/yolo/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/opt/conda/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '40177', '/home/.config/Ultralytics/DDP/_temp_1dpet89e139626003118304.py']' returned non-zero exit status 1.
> ```

To add some information, I tried to use single GPU for training and it was normal

**Comment by JulioZhao97** [comment]
What torch and cuda version are you using? Can you pleas try lower torch version such as ```torch==2.1.0+cu113```.

**Comment by whale1008** [comment]
torch version is 2.1.0+cu118

**Comment by JulioZhao97** [comment]
![image](https://github.com/user-attachments/assets/1a4957d3-118b-4dca-a4a0-f0e4bf1fc207)
looks like a bug about model loading requires ```yolov8n.pt```, when you run multi-gpu training, can you see a log information about downloading ```yolov8n.pt```? I 
![image](https://github.com/user-attachments/assets/7398e6bd-4f9d-4e18-a49c-2f06482dead4)

**Comment by JulioZhao97** [comment]
![image](https://github.com/user-attachments/assets/27ac4ff5-fd00-4432-b585-1e054524eecb)
Meanwhile this is very strange, could you please run ```conda list | grep ultralytics``` and which ```ultralytics``` version you installed?

**Comment by whale1008** [comment]
Thank you for your reply.
ultralytics version is 8.3.0
ultralytics-thop version is 2.0.0

**Comment by JulioZhao97** [comment]
> Thank you for your reply. ultralytics version is 8.3.0 ultralytics-thop version is 2.0.0

I see, could you please try ```ultralytics ==8.1.34```?

**Comment by whale1008** [comment]
It seems that there is no difference between the previous error.

**Comment by JulioZhao97** [comment]
Could you please try download [yolov8n.pt](https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt) and put it under your ```weight_dir```? ```weight_dir``` can be specified in ```~/.config/Ultralytics/settings.yaml```

**Comment by JulioZhao97** [comment]
> I did this, but it still didn't work.
> 
> Because ultralytics can train normally, I added the code to ultralytics and now it can train normally.
> 
> Although I don't know why, at least it can be trained. Thank you very much for your continued response to me. If I can find the reason, I will update you again.

You're welcome! I have one question, could you please specify 
what did you do in ```I added the code to ultralytics and now it can train normally.```? Much appreciated!

**Comment by whale1008** [comment]
The original code is stuck at "dist.broadcast(self.amp, src=0)", and AMP will not appear: checks passed

I added all G2L_CRM related content to ultralytics. Ultralytics does not have a dedicated yolov10 post-processing, so I am not sure about the impact on the training indicators.
