### ISSUE TITLE
FileNotFoundError with Dataset YAML File in Custom Training Setup

### ISSUE THREAD

**Issue by ByungilYun** [opendatalab/DocLayout-YOLO#25]
Hi there! Thank you for making this great code available.

I'm trying to train a model using your code, but I’m encountering the following error:

`python train.py --data dla_data_all_container_new --model m-doclayout --epoch 500 --image-size 1600 --batch-size 8 --project public_dataset/doclaynet --plot 1 --optimizer SGD --lr0 0.02 --pretrain /workspace/DocLayout-YOLO/model/doclayout_yolo_docsynth300k_imgsz1600.pt`

`
engine/trainer: task=detect, mode=train, model=/workspace/DocLayout-YOLO/model/doclayout_yolo_docsynth300k_imgsz1600.pt, data=dla_data_all_container_new.yaml, ...
`

Error traceback : 

`File "/workspace/DocLayout-YOLO/doclayout_yolo/engine/trainer.py", line 139, in __init__
    self.data = check_det_dataset(self.args.data)
File "/workspace/DocLayout-YO/doclayout_yolo/data/utils.py", line 338, in check_det_dataset
    file = check_file(dataset)
File "/workspace/DocLayout-YO/doclayout_yolo/utils/checks.py", line 500, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'dla_data_all_container_new.yaml' does not exist
`

I've stored the **dla_data_all_container_new dataset** under **/data1/workspace/Data/DLA**, and I’ve set **datasets_dir: /data1/workspace/Data/DLA** in **settings.yaml.** Could you clarify if a file like dla_data_all_container_new.yaml should be generated automatically following the structure mentioned in your README, or do I need to create it manually?

Thanks in advance for your help!

**Comment by JulioZhao97** [comment]
Hello! You should create a dataset ```yaml``` file under ```doclayout_yolo/cfg/datasets```, and you can reference the ```d4la.yaml``` and ```doclaynet.yaml``` to construct your yaml file. If you have any other questions, please let me know!
