### ISSUE TITLE
 DocSynth300K dataset数据标签

### ISSUE THREAD

**Issue by njustczr** [opendatalab/DocLayout-YOLO#26]
我运行完format_docsynth300k.py脚本后，label下面的txt标签文件，我打开一个看到类似这种格式的
48 0.3753874410855887 0.5664773929952223 0.6084899411254765 0.5664773929952223 0.6084899411254765 0.8952891364242538 0.3753874410855887 0.8952891364242538
有格式说明吗，后面的8个数应该是框的顺时针归一化坐标，前面那个48是类别，但是类别数怎么这么大

不是就10种类别吗？
names: {0: 'title', 1: 'plain text', 2: 'abandon', 3: 'figure', 4: 'figure_caption', 5: 'table', 6: 'table_caption', 7: 'table_footnote', 8: 'isolate_formula', 9: 'formula_caption'}

**Comment by JulioZhao97** [comment]
您好，10种类别是下游微调数据集docstructbench的类别，一共十种；docsynth300k由于使用了M6Doc种的元素，总共包含74种类别，可以参考（现已更新到主分支）

https://github.com/opendatalab/DocLayout-YOLO/blob/119996a102e383c15a9fb0897ff038215ccfaf22/doclayout_yolo/cfg/datasets/docsynth300k.yaml#L16-L91
