### ISSUE TITLE
mesh-candidate_bestfit

### ISSUE THREAD

**Issue by lyc728** [opendatalab/DocLayout-YOLO#29]
你好 看了关于数据生成的代码，是基于下载的图片和annotation_file.json 进行生成的，但是原始的标签有70多类 我现在想生成适配训练代码的10类别，需要怎么操作呢？

**Comment by JulioZhao97** [comment]
您好！
Mesh-candidate Bestfit是使用的M6Doc test中的元素和类别，对应类别为如下：
https://github.com/opendatalab/DocLayout-YOLO/blob/119996a102e383c15a9fb0897ff038215ccfaf22/doclayout_yolo/cfg/datasets/docsynth300k.yaml#L16-L91

如果您想自定义生成数据的类别，有如下方法：
1. 使用别的数据集元素进行生成。例如使用publaynet元素进行生成（包含五类），需要自行构建元素图片和标注文件
2. 重新映射类别。例如将M6Doc test中细粒度的类别映射到你所需要的十个类别（例如QR code->figure, weather forcast->figure），需要重构标注文件

**Comment by lyc728** [comment]
是要对annotation_file.json进行重构吗？这个文件的内容是什么呢

**Comment by JulioZhao97** [comment]
> 是要对annotation_file.json进行重构吗？这个文件的内容是什么呢

您好：是的，这个文件的内容是包含了原始元素的数据集（例如M6Doc test）的COCO格式的标注，格式类似于：

```json
{
    "images": [...],
    "annotations": [
        {
            "image_id": xxx,
            "instance_id": xxx,
            "category_id": xxx,
            "bbox": [...]
        }
    ],
    "categories": [...]
}
```

详细可以参考下载链接中提供的文件
