### ISSUE TITLE
Huggingface link for DocStructBench

### ISSUE THREAD

**Issue by Mobius1D** [opendatalab/DocLayout-YOLO#33]
Hello there,

It would be great if you could release the hugging face dataset link or a link in any other for DocStructBench. I tried finding but I wasn't able to get. 

Please check and get back on the same.

**Comment by JulioZhao97** [comment]
Hello, thanks for your interest on our work, unfortunatelly due to license restrictions DocStructBench cannot be released now. If we have plans for releasing DocStructBench we will update as soon as possible.
