### ISSUE TITLE
在预训练权重上微调自己的数据集会卡住

### ISSUE THREAD

**Issue by njustczr** [opendatalab/DocLayout-YOLO#34]
只要单机多卡训练就会卡住
![image](https://github.com/user-attachments/assets/54240baf-7a76-401f-8a0d-d555ed903c4d)
一直卡在这，不知道什么原因

**Comment by JulioZhao97** [comment]
您好，感谢反馈；您ctrl+C然后给一下详细的traceback信息呢？

**Comment by njustczr** [comment]
> 您好，感谢反馈；您ctrl+C然后给一下详细的traceback信息呢？

![image](https://github.com/user-attachments/assets/6e43bb72-a474-4c3f-be78-a82ad9bd8c2d)
我现在把 assert amp_allclose(YOLO("yolov8n.pt"), im)  这行卡住的代码注释掉可以一机多卡训练了
