### ISSUE TITLE
请问300k数据集的category name在哪~

### ISSUE THREAD

**Issue by linchen111** [opendatalab/DocLayout-YOLO#36]

**Comment by JulioZhao97** [comment]
您好，300K的类别名在如下：
https://github.com/opendatalab/DocLayout-YOLO/blob/119996a102e383c15a9fb0897ff038215ccfaf22/doclayout_yolo/cfg/datasets/docsynth300k.yaml#L16-L91

**Comment by linchen111** [comment]
> 您好，300K的类别名在如下：
> 
> https://github.com/opendatalab/DocLayout-YOLO/blob/119996a102e383c15a9fb0897ff038215ccfaf22/doclayout_yolo/cfg/datasets/docsynth300k.yaml#L16-L91

好的，感谢。请问里面的八个坐标是啥呢
