### ISSUE TITLE
doclayout_yolo_ft.pt对应DocLayout-YOLO模型对应的标签有哪些

### ISSUE THREAD

**Issue by Jiangyangya** [opendatalab/DocLayout-YOLO#38]
跟300K数据集的标签有何联系？

**Comment by JulioZhao97** [comment]
您好，```doclayout_yolo_ft.pt```的类别可以参考此处，和300K的标签没有直接联系：
https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/yolo.py#L18-L29

**Comment by Jiangyangya** [comment]
那这个模型是基于300k数据集的预训练模型微调得来的吗，还是其他的方式

**Comment by JulioZhao97** [comment]
您好，是300K数据集的预训练模型微调来的

**Comment by Jiangyangya** [comment]
好的，谢谢您的讲解~
