### ISSUE TITLE
关于数据生成算法

### ISSUE THREAD

**Issue by Jiangyangya** [opendatalab/DocLayout-YOLO#39]
您好，我在readme中有看到元素池和标注示例，这一块有元素池生成的实现代码吗？

**Comment by Jiangyangya** [comment]
想问一下对于数据生成算法生成的图片，元素的位置特征是不是没有了？比如页眉页脚这一类数据，它的位置都是出现在头尾，这样生成的图片属于是偏向于做预训练模型而不是微调训练是吗？

**Comment by JulioZhao97** [comment]
> 想问一下对于数据生成算法生成的图片，元素的位置特征是不是没有了？比如页眉页脚这一类数据，它的位置都是出现在头尾，这样生成的图片属于是偏向于做预训练模型而不是微调训练是吗？

您好：是的，我们尝试过将位置先验融入到生成数据集里，一方面M6Doc训练集获取不到，我们使用的测试集元素比较少，比较难拟合不同元素位置分布，其次我们发现这样做貌似对预训练模下有微调效果型影响不大
