### ISSUE TITLE
训练和推理时的尺寸问题。

### ISSUE THREAD

**Issue by huihuiustc** [opendatalab/DocLayout-YOLO#40]
非常棒的工作，以下我有一个小问题；
训练是的输入图像是1600，推理时好像用1024更好。当我用图像尺寸为1600的时候，这张图像的表格会检测有问题，用1024反而更好。
![原始图像](https://github.com/user-attachments/assets/7fa0b802-9f0b-4386-9782-4dc6dc7a20f5) 
![推理图像](https://github.com/user-attachments/assets/32fd1e62-58b9-4cb7-9a73-e90c30262e0a)

**Comment by JulioZhao97** [comment]
您好，感谢反馈：
1. 直觉上感受训练和推理分辨率相同应该是最优的
2. 训练和推理的分辨率过高（例如1600），由于模型的原因（例如感受野不足，模型小特征不足等）会导致过大目标识别不全
3. 您可以根据实际需求设置最优的分辨率，如果您的数据里几乎没有这样特别大的目标，可以适当提高训练推理分辨率；反之需要降低训练推理分辨率。例如repo里提供的模型训练测试分辨率设置为1024，对大目标缺失和小目标识别平衡比较好
