### ISSUE TITLE
调整iou参数的值模型输出结果一样

### ISSUE THREAD

**Issue by jinxujinxu** [opendatalab/DocLayout-YOLO#41]
首先感谢作者开源这么好的工作！

在运行下面代码时：
import cv2
from doclayout_yolo import YOLOv10

# Load the pre-trained model
model = YOLOv10("path/to/provided/model")

# Perform prediction
det_res = model.predict(
    "path/to/image",   # Image to predict
    imgsz=1024,        # Prediction image size
    conf=0.2,          # Confidence threshold
    iou=0.45,
    device="cuda:0"    # Device to use (e.g., 'cuda:0' or 'cpu')
)

# Annotate and save the result
annotated_frame = det_res[0].plot(pil=True, line_width=5, font_size=20)
cv2.imwrite("result.jpg", annotated_frame)

调整"iou"参数的值，模型输出结果没有变化，但在https://huggingface.co/spaces/opendatalab/DocLayout-YOLO中调整"iou"参数的值，模型输出结果有变化，请问什么原因？

**Comment by JulioZhao97** [comment]
您好！
在默认yolov10中由于没有NMS后处理，传入iou_thr是无效的，如果您需要加入NMS操作，可以参考huggingface demo中的代码:
https://huggingface.co/spaces/opendatalab/DocLayout-YOLO/blob/3f02d20af1765d58cb03604da21b66e21c521494/app.py#L40-L49

**Comment by jinxujinxu** [comment]
> 您好！ 在默认yolov10中由于没有NMS后处理，传入iou_thr是无效的，如果您需要加入NMS操作，可以参考huggingface demo中的代码: https://huggingface.co/spaces/opendatalab/DocLayout-YOLO/blob/3f02d20af1765d58cb03604da21b66e21c521494/app.py#L40-L49

好的，非常感谢！
