### ISSUE TITLE
训练缺少参数

### ISSUE THREAD

**Issue by lyc728** [opendatalab/DocLayout-YOLO#42]
你好 我用自己的数据进行训练 参考了你的配置
python train.py --data doclaynet --model m-doclayout --epoch 500 --image-size 1120 --batch-size 64 --project public_dataset/doclaynet --plot 1 --optimizer SGD --lr0 0.02
发现model 这里应该是一个模型吧，这边没有公开吗？

`File "/data/DocLayout_yolo/doclayout_yolo/models/yolov10/__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "/data/DocLayout_yolo/doclayout_yolo/models/yolov10/model.py", line 9, in <module>
    class YOLOv10(Model, PyTorchModelHubMixin, repo_url="https://github.com/opendatalab/DocLayout-YOLO", pipeline_tag="object-detection", license="agpl-3.0"):
TypeError: __init_subclass__() takes no keyword arguments`

**Comment by lyc728** [comment]
初始化 我删除了一些参数是可以了
class YOLOv10(Model):

**Comment by lyc728** [comment]
还有为什么每次训练都回去下载模型啊 这样好慢的

**Comment by JulioZhao97** [comment]
您好，感谢反馈：
1. 目前经过测试训练应该是正常的，具体原因可以提供更多报错信息供参考？相关改动可以参考：https://github.com/opendatalab/DocLayout-YOLO/pull/6
2. 这个是原始ultralytics代码中自带的功能，考虑到后续需求，我们会对这个问题进行修改

**Comment by lyc728** [comment]
> 还有为什么每次训练都回去下载模型啊 这样好慢的 AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n... Downloading https://github.com/doclayout_yolo/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...

那请问为什么最开始下载是yolov8 不应该用yolov10的模型进行训练吗

**Comment by JulioZhao97** [comment]
> > 还有为什么每次训练都回去下载模型啊 这样好慢的 AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n... Downloading https://github.com/doclayout_yolo/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
> 
> 那请问为什么最开始下载是yolov8 不应该用yolov10的模型进行训练吗

您好，因为这个问题是原始ultralytics yolo库中就有的，基于这一套代码的都会有需要下载yolov8这个问题，例如yolov10也会有，而我们的代码基于yolov10的话同样也有这个问题，训练时并没有使用到相关权重
