### ISSUE TITLE
缺少yaml文件

### ISSUE THREAD

**Issue by huskycreatenode** [opendatalab/DocLayout-YOLO#43]
下载完训练集，执行
python train.py --data d4la --model m-doclayout --device cpu --epoch 500 --image-size 1600 --batch-size 64 --project public_dataset/D4LA --plot 1 --optimizer SGD --lr0 0.04的时候出现
RuntimeError: Dataset 'd4la.yaml' error  
Dataset 'd4la.yaml' images not found

**Comment by JulioZhao97** [comment]
您好，感谢反馈
1. 您用的何种安装方式？
2. ultralytics config文件内容？

**Comment by huskycreatenode** [comment]
@JulioZhao97 
您好，我是在readme中执行了
![image](https://github.com/user-attachments/assets/ac035b2a-aff1-4f17-9b7e-9a8b1f4e4b60)
这个cao操作，下载了d4la数据集，但是数据集中我并没有找到 d4la.yaml文件，我不确定yml文件是否和
![image](https://github.com/user-attachments/assets/462c9bf5-1077-4fed-865b-528ff3ffb4fa)
这一步有关，这一步我直接跳过了

**Comment by huskycreatenode** [comment]
@JulioZhao97
您好，我是在readme中执行了
![image](https://github.com/user-attachments/assets/4ee0ae5f-ddd8-465b-a143-e8a2a302627e)
这个操作，下载了d4la数据集，但是数据集中我并没有找到 d4la.yaml文件，我不确定yml文件是否和
![image](https://github.com/user-attachments/assets/13be784e-64b7-4660-927b-a1df13ee5db8)
这一步有关，这一步我直接跳过了，因为我没找到这个文件

**Comment by JulioZhao97** [comment]
@huskycreatenode 数据集文件在 ```doclayout_yolo/cfg/datasets/d4la.yaml```，设置数据根目录是需要执行的，设置好了以后程序会自动找到数据集

**Comment by huskycreatenode** [comment]
谢谢，这个问题已经解决了，非常感谢
