### ISSUE TITLE
请问 pretrain 的 DocLayout-YOLO 是训练了多少个 epoch 的权重呢

### ISSUE THREAD

**Issue by yjc11** [opendatalab/DocLayout-YOLO#44]
请问 pretrain 的 DocLayout-YOLO 是训练了多少个 epoch 的权重呢，感谢

**Comment by JulioZhao97** [comment]
您好，训练了30个epoch

**Comment by yjc11** [comment]
好的，感谢回复！

**Comment by sralvins** [comment]
> 您好，训练了30个epoch

请问预训练过程中有使用mosaic增强吗，使用的是ultralytics的默认参数吗？在该任务上，对mAP有影响吗

**Comment by JulioZhao97** [comment]
@sralvins 您好，这个没有特意测试过，默认是使用了mosaic增强的，除了命令中的一些参数其他都是默认的
