### ISSUE TITLE
docsynth300k 类别

### ISSUE THREAD

**Issue by hinakurumi** [opendatalab/DocLayout-YOLO#45]
你好，docsynth300k 是和M6的类别对应吗？yolo的label文件的id 对应的类别可以提供吗？

**Comment by JulioZhao97** [comment]
您好：是的，docsynth300k中类别和M6Doc是对应的，对应的类别在```doclayout_yolo/cfg/datasets/docsynth300k.yaml```

**Comment by hinakurumi** [comment]
谢谢，找到了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhiyuan Zhao ***@***.***&gt;
发送时间: 2024年11月18日 09:56
收件人: opendatalab/DocLayout-YOLO ***@***.***&gt;
抄送: hinakurumi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [opendatalab/DocLayout-YOLO] docsynth300k 类别 (Issue #45)





 
Closed #45 as completed.
