### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolov8n.pt'

### ISSUE THREAD

**Issue by huskycreatenode** [opendatalab/DocLayout-YOLO#46]
你好，我想训练我的doclayout_yolo_ft.py模型
![image](https://github.com/user-attachments/assets/7efba60d-4048-4398-89ab-ab28d7be7d3f)
在windows 下，我可以正常的进行训练，但是在GPU服务器下，他总是会自动地去下载yolov8，我在train.py代码端没找到和yolov8有关的信息，我应该怎么解决？
![image](https://github.com/user-attachments/assets/305a449f-cdd8-45f7-8458-1b853a41c8e3)
我的训练命令为：
python train.py --data d4la --model m-doclayout --pretrain /data/model/doclayout_yolo_ft.pt --device 0 --epoch 500 --image-size 1600 --batch-size 64 --project datasets/D4LA --plot 1 --optimizer SGD --lr0 0.04

**Comment by huskycreatenode** [comment]
![image](https://github.com/user-attachments/assets/0cf7155d-ee5b-4e54-b858-32a3b11974aa)
应该是这个，所以CPU可以正常运行，我所疑惑的是为什么GPU要依赖于yolov8n.pt，这个amp_allclose(YOLO("yolov8n.pt"), im)的作用是什么呢？万分感谢解答

**Comment by JulioZhao97** [comment]
您好：这个功能是原始```ultralytics```中自带的，您可以通过下载```yolov8n.pt```然后放置到项目根目录，或者通过以下解决方法：https://github.com/opendatalab/DocLayout-YOLO/issues/34
