### ISSUE TITLE
输出元素区域存在重叠

### ISSUE THREAD

**Issue by guici123** [opendatalab/DocLayout-YOLO#50]
同一个输出元素区域可能有多个元素标签或者一个元素标签区域包含在另一个元素标签区域内，这种除了阈值还有什么方法处理吗？

**Comment by JulioZhao97** [comment]
您好，感谢反馈！这种情况可以通过
1. 调整NMS阈值
2. 通过bbox之间的overlap检查是否有大框包小框
等方法来处理，更多的后处理您可以参考一些PDF提取工具例如[MinerU](https://github.com/opendatalab/MinerU)，会有更多的后处理规则和方案

**Comment by guici123** [comment]
> 您好，感谢反馈！这种情况可以通过
> 
> 1. 调整NMS阈值
> 2. 通过bbox之间的overlap检查是否有大框包小框
>    等方法来处理，更多的后处理您可以参考一些PDF提取工具例如[MinerU](https://github.com/opendatalab/MinerU)，会有更多的后处理规则和方案

好的 感谢您的建议
