### ISSUE TITLE
Where can I tune the NMS threshold

### ISSUE THREAD

**Issue by XsLangley** [opendatalab/DocLayout-YOLO#52]
Hi,

Many thanks for releasing such a great model for layout detection! It helps a lot!
However, I found that the local demo code only allows tuning the confidence, while the online demo supports tuning both the confidence and NMS IoU threshold. I would like to know how I can tune the NMS IoU in the sample code, just like what I can do in the online demo. 
Thanks a lot.

**Comment by JulioZhao97** [comment]
Hello, thanks for you interest in our work!
You can refer to ```app.py``` in the online demo file and adjust NMS threshold like that: 
https://huggingface.co/spaces/opendatalab/DocLayout-YOLO/blob/3f02d20af1765d58cb03604da21b66e21c521494/app.py#L40-L49
