### ISSUE TITLE
作者您好，我有两个问题还请请教一下。1.我用demo.py测试assets中的图片报错，model用的是yolov10b.pt,报错内容是class YOLOv10(Model, PyTorchModelHubMixin, repo_url="https://github.com/opendatalab/DocLayout-YOLO", pipeline_tag="object-detection", license="agpl-3.0"):  TypeError: YOLOv10.__init_subclass__() takes no keyword arguments,请问该如何解决。2.如果训练自己做的类似D4LA数据集的数据集，是不是用train.py进行训练呢，我看train

### ISSUE THREAD

**Issue by NorthBlueSky** [opendatalab/DocLayout-YOLO#55]

**Comment by NorthBlueSky** [comment]
1.我用demo.py测试assets中的图片报错，model用的是yolov10b.pt,报错内容是class YOLOv10(Model, PyTorchModelHubMixin, repo_url="https://github.com/opendatalab/DocLayout-YOLO", pipeline_tag="object-detection", license="agpl-3.0"):  TypeError: YOLOv10.__init_subclass__() takes no keyword arguments,请问该如何解决。2.如果训练自己做的类似D4LA数据集的数据集，是不是用train.py进行训练呢，我看train.py中要规定image-size，我的数据集的图片大小不等，请问该如何设置呢

**Comment by JulioZhao97** [comment]
您好，感谢反馈！
1. 请问您使用的是yolov10官方提供的```yolov10b.pt```还是自己用DocLayout-YOLO repo训练的？由于yolo的checkpoint中包含的不仅是权重，还有模型对应的python类（比如nn.Module），类代码变了会导致类似无法加载的现象出现
2. 您可以根据元素尺寸来决定image-size，如果几乎没有特别大的元素（例如整页的表格），可以将image-size设置大一些例如1600（但是不推荐，因为会出现大目标识别不全问题），如果想避免这个问题，同时保证对小物体识别精度，可以设置为1024；至于图片大小不等问题，具体是从多少到多少？预处理会将图片缩放到长边1024这个尺寸，使用这种设定即可，您也可以在```cfg/configs/default.cfg```来打开```multi-scale```设置开启多尺度训练

**Comment by JulioZhao97** [comment]
> > 您好，感谢反馈！
> > 
> > 1. 请问您使用的是yolov10官方提供的`yolov10b.pt`还是自己用DocLayout-YOLO repo训练的？由于yolo的checkpoint中包含的不仅是权重，还有模型对应的python类（比如nn.Module），类代码变了会导致类似无法加载的现象出现
> > 2. 您可以根据元素尺寸来决定image-size，如果几乎没有特别大的元素（例如整页的表格），可以将image-size设置大一些例如1600（但是不推荐，因为会出现大目标识别不全问题），如果想避免这个问题，同时保证对小物体识别精度，可以设置为1024；至于图片大小不等问题，具体是从多少到多少？预处理会将图片缩放到长边1024这个尺寸，使用这种设定即可，您也可以在`cfg/configs/default.cfg`来打开`multi-scale`设置开启多尺度训练
> 
> 我用的yolov10官方提供的yolov10b.pt,想测试一下效果，结果出现类似报错

官方提供的权重是不可以load的，因为类定义不一样了

**Comment by NorthBlueSky** [comment]
> > > 您好，感谢反馈！
> > > 
> > > 1. 请问您使用的是yolov10官方提供的`yolov10b.pt`还是自己用DocLayout-YOLO repo训练的？由于yolo的checkpoint中包含的不仅是权重，还有模型对应的python类（比如nn.Module），类代码变了会导致类似无法加载的现象出现
> > > 2. 您可以根据元素尺寸来决定image-size，如果几乎没有特别大的元素（例如整页的表格），可以将image-size设置大一些例如1600（但是不推荐，因为会出现大目标识别不全问题），如果想避免这个问题，同时保证对小物体识别精度，可以设置为1024；至于图片大小不等问题，具体是从多少到多少？预处理会将图片缩放到长边1024这个尺寸，使用这种设定即可，您也可以在`cfg/configs/default.cfg`来打开`multi-scale`设置开启多尺度训练
> > 
> > 
> > 我用的yolov10官方提供的yolov10b.pt,想测试一下效果，结果出现类似报错
> 
> 官方提供的权重是不可以load的，因为类定义不一样了，如果你想测试官方提供的模型需要用他们的代码

不好意思麻烦您了作者，刚才我用doclayout_yolo_docstructbench_imgsz1024.pt和doclayout_yolo_docsynth300k_imgsz1600.pt,输入指令python .\demo.py --model E:\BaiduNetdiskDownload\DocLayout-YOLO_datasetes\my_test_datasets\DocLayout-YOLO\weights\doclayout_yolo_docstructbench_imgsz1024.pt --image-path E:\BaiduNetdiskDownload\DocLayout-YOLO_datasetes\my_test_datasets\DocLayout-YOLO\assets\example\exam_paper.jpg,依然报错File "E:\BaiduNetdiskDownload\DocLayout-YOLO_datasetes\my_test_datasets\DocLayout-YOLO\doclayout_yolo\models\yolov10\model.py", line 9, in <module>
    class YOLOv10(Model, PyTorchModelHubMixin, repo_url="https://github.com/opendatalab/DocLayout-YOLO", pipeline_tag="object-detection", license="agpl-3.0"):
TypeError: YOLOv10.__init_subclass__() takes no keyword arguments，不知道是什么情况

**Comment by JulioZhao97** [comment]
@NorthBlueSky 你这边是怎么安装的，是from source安装的嘛？

**Comment by NorthBlueSky** [comment]
> @NorthBlueSky 你这边是怎么安装的，是from source安装的嘛？

谢谢作者，已经解决了

**Comment by JulioZhao97** [comment]
> > @NorthBlueSky 你这边是怎么安装的，是from source安装的嘛？
> 
> 谢谢作者，已经解决了

好奇怎么解决的..

**Comment by NorthBlueSky** [comment]
> > > @NorthBlueSky 你这边是怎么安装的，是from source安装的嘛？
> > 
> > 
> > 谢谢作者，已经解决了
> 
> 好奇怎么解决的..

应该是环境安装出了问题，我重新pip install -e .就好啦

**Comment by NorthBlueSky** [comment]
> > > @NorthBlueSky 你这边是怎么安装的，是from source安装的嘛？
> > 
> > 
> > 谢谢作者，已经解决了
> 
> 好奇怎么解决的..

作者您好，train.py的data是数据集的路径，那project参数是什么呢

**Comment by JulioZhao97** [comment]
@NorthBlueSky project根据个人喜欢设置，训练相关的模型和日志会保存在此文件夹下

**Comment by NorthBlueSky** [comment]
> @NorthBlueSky project根据个人喜欢设置，训练相关的模型和日志会保存在此文件夹下

作者您好，我在使用doclayout_yolo_docstructbench_imgsz1024.pt或者doclayout_yolo_docsynth300k_imgsz1600.pt作为model参数运行train.py都提示确实yaml文件，请问这个文件是不是要自己定义，如果定义的话，内容是我自己数据集的标签还是模型原始数据集的标签呀

**Comment by JulioZhao97** [comment]
> > @NorthBlueSky project根据个人喜欢设置，训练相关的模型和日志会保存在此文件夹下
> 
> 作者您好，我在使用doclayout_yolo_docstructbench_imgsz1024.pt或者doclayout_yolo_docsynth300k_imgsz1600.pt作为model参数运行train.py都提示确实yaml文件，请问这个文件是不是要自己定义，如果定义的话，内容是我自己数据集的标签还是模型原始数据集的标签呀

@NorthBlueSky 
1. 如果是训练自己的数据集，这个是需要自己去组织的，组织方式参考我给出的```DocLayNet```或者```D4LA```就可以
2. 如果是训练repo中给出的公开数据集，可以给一下详细的报错信息？

**Comment by NorthBlueSky** [comment]
> > > @NorthBlueSky project根据个人喜欢设置，训练相关的模型和日志会保存在此文件夹下
> > 
> > 
> > 作者您好，我在使用doclayout_yolo_docstructbench_imgsz1024.pt或者doclayout_yolo_docsynth300k_imgsz1600.pt作为model参数运行train.py都提示确实yaml文件，请问这个文件是不是要自己定义，如果定义的话，内容是我自己数据集的标签还是模型原始数据集的标签呀
> 
> @NorthBlueSky
> 
> 1. 如果是训练自己的数据集，这个是需要自己去组织的，组织方式参考我给出的`DocLayNet`或者`D4LA`就可以
> 2. 如果是训练repo中给出的公开数据集，可以给一下详细的报错信息？
我用的是我自己的数据集，训练的时候提示缺少yaml文件如图
![image](https://github.com/user-attachments/assets/667883df-a6be-4db3-bfcb-5e297e05d0c9)
但是我查看您给的D4LA数据集或者DocLayNet数据集，并没有在数据集中找到可以供我参考的yaml文件，所有我就自己编写yaml文件，这是我的yaml文件，明明存在，请问缺少什么东西呢
![image](https://github.com/user-attachments/assets/93bb3392-92f3-4e70-a335-d42eccef991f)

**Comment by JulioZhao97** [comment]
@NorthBlueSky 
1. train.py传入的这个```--model```指的是模型尺寸，比如m-doclayout，或者s/m/l之类的，具体可以参考```cfg/models/v10```下面的模型配置文件，去掉```yolov10```就是模型尺寸参数
2. 如果想加载预训练模型，需要加入```--pretrain doclayout_yolo_docsynth300k_imgsz1600.pt```即可
具体可以参考https://github.com/opendatalab/DocLayout-YOLO?tab=readme-ov-file#training-and-evaluation这里的各种配置下的训练测试
