### ISSUE TITLE
配置小問題

### ISSUE THREAD

**Issue by milk333445** [opendatalab/DocLayout-YOLO#57]
大佬您好：
我在使用您的工具時遇到了一些問題，想向您請教：
1. 關於訓練微調
是否可以直接使用 ultralytics 提供的腳本進行模型的微調？因為我使用的是 Windows 系統，沒有找到 Ultralytics/settings.yaml 文件，所以想說直接使用 ultralytics 腳本進行訓練，例如訓練 doclayout_yolo 的模型。還是說需要使用您提供的特定腳本來完成微調呢？感謝解惑！
2. 關於 data.yaml 的配置
如果使用 doclayout_yolo_docstructbench_imgsz1024.pt 模型在 D4LA 數據集上進行微調，D4LA 中的類別數似乎超過了預訓練模型的 10 類，與預訓練類別不完全對應。那麼是否需要手動將 D4LA 的類別對齊為預訓練模型的 10 類？還是可以直接使用您提供的微調指令來處理這種情況？

**Comment by JulioZhao97** [comment]
@milk333445 
您好，感谢关注！
1. 我没有太理解您的意思，如果您指的是```settings.yaml```的话这个应该只会影响数据集的位置，当修改了```settings.yaml```中的数据集配置后应该就可以直接使用repo中提供的```train.py```就可以微调，至于在windows中的路径您可以在ultralytics中进一步询问
2. ```doclayout_yolo_docstructbench_imgsz1024 .pt```是在```DocStructBench```上微调得到的，具体类别和解释可以参考[arxiv paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=K0BNv0YAAAAJ&citation_for_view=K0BNv0YAAAAJ:zYLM7Y9cAGgC)；另外**下游的微调类别不需要和预训练模型类别对应，直接加载即可**

如果还有其他问题，欢迎反馈，我会及时回复！

**Comment by milk333445** [comment]
了解謝謝!，那我還有個小問題想請教，配置完settings.yaml應該就可以用指令找到數據集，但不需要配置訓練測試還有類別對應的yaml嗎，例如下面這種
path: ../datasets/coco8 # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images
test: # test images (optional)

# Classes
names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: airplane
是不需要配置就可以自動識別嗎?謝謝回復!

**Comment by JulioZhao97** [comment]
@milk333445 需要对应的yaml的，您可以参考我给出的```D4LA```以及```DocLayNet```数据格式，以及```cfg/datasets```下面的配置

**Comment by milk333445** [comment]
解決了，謝謝您!
