### ISSUE TITLE
关于微调的几个问题

### ISSUE THREAD

**Issue by flow3rdown** [opendatalab/DocLayout-YOLO#58]
您好，非常好的项目，想请教一下微调的几个问题：
1. 基于哪个权重来微调会更好一点？
2. 需要多少的数据量呀？
3. 学习率、训练轮次这些需要怎么设置的？

感谢！

**Comment by JulioZhao97** [comment]
您好：
1. 基于```DocSynth300K```预训练的权重[```docsynth300k_pretrained.pt```](https://huggingface.co/juliozhao/DocLayout-YOLO-D4LA-Docsynth300K_pretrained/blob/main/doclayout_yolo_d4la_imgsz1600_docsynth_pretrain.pt)适合微调，其他都是微调后的权重
2. 如果您指的是微调的话，检测需要的数据量比较少，例如DocStructBench包含了4个类型共10K张文档图像，**但是微调数据多样性比较重要**
3. 初始学习率一般设置为0.01或者0.02即可，训练轮次默认500轮，会保存在验证集上最好的ckpt为```best.pt```

**Comment by JulioZhao97** [comment]
@flow3rdown 这个模型貌似不在DocLayout-YOLO的模型中？具体链接可以发一下

**Comment by flow3rdown** [comment]
> @flow3rdown 这个模型貌似不在DocLayout-YOLO的模型中？具体链接可以发一下

这个是PDF-Extract-Kit提供的模型：https://huggingface.co/opendatalab/PDF-Extract-Kit-1.0/tree/main/models/Layout/YOLO

**Comment by JulioZhao97** [comment]
@flow3rdown 这个是使用DocStructBench在DocSynth300K上微调得到的模型，不确定是否适合继续微调

**Comment by flow3rdown** [comment]
好的，感谢！ 还有一个小问题想请教一下，由于D4LA、DocLayNet 和 DocStructBench的类别数据不一样，是如何进行评估对比的呢？做了标签的映射吗？

**Comment by JulioZhao97** [comment]
@flow3rdown 您说的评估对比指的意思是？

**Comment by flow3rdown** [comment]
比如论文中的表1和表2，是如何一起对比的结果？

**Comment by JulioZhao97** [comment]
![image](https://github.com/user-attachments/assets/c27553fd-bf2f-457d-8524-d0308d79103e)
以b表1为例，没有不同数据集的横向对比，这个每一列是在不同数据集的评测集上的结果，需要每一行对比每一个模块的作用，表2也是同样，每一列是不同数据集的结果，每一行对比不同模型的效果

**Comment by flow3rdown** [comment]
明白了，感谢您的回复！
