### ISSUE TITLE
作者您好，我在用自己的数据集微调模型时，训练到200轮左右时突然中断，接连两次都是这种情况，提示Conv层有问题

### ISSUE THREAD

**Issue by NorthBlueSky** [opendatalab/DocLayout-YOLO#59]
我在用自己的数据集训练模型，然后200轮左右突然退出了，这是报错截图
![image](https://github.com/user-attachments/assets/3281a051-30ea-452d-989d-06dab7464d8b)

![image](https://github.com/user-attachments/assets/51341953-3f15-402e-9cf3-8b917817cbba)
请问该如何解决呢

**Comment by JulioZhao97** [comment]
@NorthBlueSky 您好，这个是因为训练中止了（100个epoch之内在验证集上没有进一步提升了）
![image](https://github.com/user-attachments/assets/aea2891a-940c-4531-9edb-3e779bf41049)

最后这个报错是一个已知的bug，暂时还没修复但是不影响，您可以使用```val.py```来测试最佳模型```best.pt```的效果
