### ISSUE TITLE
作者大佬您好，我在测试的时候发现DocStructBench的推理效果好像也比较适应我的运用场景，你那边能给我一下这个模型对应的数据集配置吗，比如包含类别的yaml文件或者数据集下载链接，感谢感谢！！

### ISSUE THREAD

**Issue by BajieZheng** [opendatalab/DocLayout-YOLO#60]

**Comment by JulioZhao97** [comment]
您好，目前由于版权原因，DocStructBench数据集无法公开，其类别对应可以参考：
https://github.com/opendatalab/PDF-Extract-Kit/blob/47f9055f7e5cf80cce9cff39cff0eead61ec09cf/pdf_extract_kit/tasks/layout_detection/models/yolo.py#L17-L29
