### ISSUE TITLE
online demo model

### ISSUE THREAD

**Issue by cryingjin** [opendatalab/DocLayout-YOLO#61]
Which specific model was used in the online demo?  
Is it the one that reported the highest performance, `'juliozhao/DocLayout-YOLO-DocLayNet-Docsynth300K_pretrained'`?

**Comment by JulioZhao97** [comment]
@cryingjin Hello! The model used in online demo is https://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/blob/main/doclayout_yolo_docstructbench_imgsz1024.pt, which is finetuned on DocStructBench
