### ISSUE TITLE
关于DocSynth300K数据集

### ISSUE THREAD

**Issue by lokking** [opendatalab/DocLayout-YOLO#62]
大佬您好，我想问一下这个数据中的类别有那些，比如说23代表什么类别？

**Comment by JulioZhao97** [comment]
@lokking 您好，DocSynth300K的类别可以参考：

https://github.com/opendatalab/DocLayout-YOLO/blob/119996a102e383c15a9fb0897ff038215ccfaf22/doclayout_yolo/cfg/datasets/docsynth300k.yaml#L17-L91

**Comment by lokking** [comment]
再麻烦大佬一下，“first-level title”是标题的级别吗？

**Comment by JulioZhao97** [comment]
@lokking 是的；由于我们使用的是M6Doc中的文档元素，关于具体的含义你可以参考M6Doc的[paper](https://arxiv.org/pdf/2305.08719)
