### ISSUE TITLE
question regarding the order of the bbox

### ISSUE THREAD

**Issue by Skyer19** [opendatalab/DocLayout-YOLO#64]
Hi there,

Thank you for providing a wonderful model.

When I used the DocLayout-YOLO to extract the bboxes from a png (from PDF) and used the bbox information in `det_res[0].boxes.data`, I find the information of the coordinates for every bbox is not in order. For example:

![image](https://github.com/user-attachments/assets/65c42c2d-f35f-41ff-b319-ebc9b5818629)

There are three bboxes, while each paragraph has one. However, the bboxes information in det_res[0].boxes.data like:

```
[[the coordinates of the bbox for the second paragraph, the confidence, the label],
[the coordinates of the bbox for the first paragraph, the confidence, the label],
[the coordinates of the bbox for the third paragraph, the confidence, the label]]
```

May I know if it is possible for me to have the above information in an order, like:

```
[[the coordinates of the bbox for the first paragraph, the confidence, the label],
[the coordinates of the bbox for the second paragraph, the confidence, the label],
[the coordinates of the bbox for the third paragraph, the confidence, the label]]
```

Thank you.

Some code is as follows:
```
import cv2
from doclayout_yolo import YOLOv10

model = YOLOv10("path/to/provided/model")

det_res = model.predict(
    "path/to/image",  
    imgsz=1024,       
    conf=0.2,          
    device="cuda:0"   
)

json_result = []
order = 1  # Start order from 1
for row in det_res[0].boxes.data: 
    xmin, ymin, xmax, ymax, confidence, cls = row.tolist()
    json_result.append({
        "bbox": [xmin, ymin, xmax, ymax],
        "confidence": confidence,
        "class": int(cls),
        "order": order
    })
    order += 1 
```

**Comment by JulioZhao97** [comment]
@Skyer19 Thanks for your interest on our work! The output of DocLayout-YOLO layout detection is not related to Reading Order. You can refer to [MinerU](https://github.com/opendatalab/MinerU), which uses a open-sourced layout reading order model to extract bbox order.
