### ISSUE TITLE
区域的位置信息获取

### ISSUE THREAD

**Issue by wodepan** [opendatalab/DocLayout-YOLO#67]
我想获取推理后，布局中每个区域的位置信息，如何拿到呢？

**Comment by JulioZhao97** [comment]
您好，以```demo.py```为例，您可以通过以下方式获取：
1. 类别：```det_res[0].boxes.cls```
2. 置信度：```det_res[0].boxes.conf```
3. bbox：```det_res[0].boxes.xyxy```

**Comment by Heyffff** [comment]
您好，我想获取原图像中的bbox应该怎么做，det_res[0].boxes.xyxy是否是resize后的？

**Comment by JulioZhao97** [comment]
@Heyffff 您好，```det_res ```中的结果就是原图尺寸上的结果
