### ISSUE TITLE
about label.yaml

### ISSUE THREAD

**Issue by lvpeng159** [opendatalab/DocLayout-YOLO#7]
i use the “doclayout_yolo_docstructbench_imgsz1024.pt” weight file，does this project have a **cls.yaml** file for this weight file to show all the classes? maybe it exists，i just can‘t find it. ：)

**Comment by JulioZhao97** [comment]
The classes to id mapping is as follows:

```python
id_to_names = {
    0: 'title', 
    1: 'plain text',
    2: 'abandon', 
    3: 'figure', 
    4: 'figure_caption', 
    5: 'table', 
    6: 'table_caption', 
    7: 'table_footnote', 
    8: 'isolate_formula', 
    9: 'formula_caption'
}
```

**Comment by JulioZhao97** [comment]
If there are any other questions, feel free to let me know!

**Comment by lvpeng159** [comment]
> If there are any other questions, feel free to let me know!

ok，Thank you for your reply response.：）
