### ISSUE TITLE
How to run the inference in npu device?

### ISSUE THREAD

**Issue by Number18-tong** [opendatalab/DocLayout-YOLO#70]

**Comment by JulioZhao97** [comment]
@Number18-tong Hello! Currently we do not plan to deploy on NPU device, but the code is based on YOLOv10, you can refer to thier repo and issue for solution.

**Comment by Number18-tong** [comment]
> @Number18-tong Hello! Currently we do not plan to deploy on NPU device, but the code is based on YOLOv10, you can refer to thier repo and issue for solution.

OK. Thanks a lot
