### ISSUE TITLE
自定义数据微调格式

### ISSUE THREAD

**Issue by katie312** [opendatalab/DocLayout-YOLO#71]
请问一下大佬们：
自定义数据集格式是这样吗？
├── images
├── labels
├── test.txt
└── train.txt

1. train，test里面放图片路径，图片命名与label命名一致，前缀为类别，此处的前缀是需要被提取做预处理吗?

2. specification_87213679_3680.pn.txt 与specification_87213679_3680.txt两种label有什么区别？看着内容是一致的

**Comment by JulioZhao97** [comment]
@katie312 
1. train.txt和test.txt中图片路径命名没有要求
2. .txt中保存的是类别和位置，例如
```txt
c 左上x 左上y 右上x 右上y 右下x 右下y 左下x 左下y
```

**Comment by katie312** [comment]
> @katie312
> 
> 1. train.txt和test.txt中图片路径命名没有要求
> 2. .txt中保存的是类别和位置，例如
> 
> ```
> c 左上x 左上y 右上x 右上y 右下x 右下y 左下x 左下y
> ```

了解，感谢！ 应该是指对应比例值？我看里面的数值都是小于1的，比如：
0 0.03761574074074074 0.12827225130890052 0.30787037037037035 0.12827225130890052 0.30787037037037035 0.1880453752181501 0.03761574074074074 0.1880453752181501 

另外想问一下.pn.txt和.txt 有什么区别呢？.pn.txt是训练的中间产物吗？

**Comment by JulioZhao97** [comment]
@katie312 我不知道哪里有.pn.txt？

**Comment by katie312** [comment]
下载的D4LA数据集里面看到的
```
 /data/xxx/DocLayout-YOLO/layout_data/D4LA/labels# ls | grep specification_87213679_3680
specification_87213679_3680.pn.txt
specification_87213679_3680.txt

```

没事，如果不需要的话我就忽略啦，感谢！

**Comment by JulioZhao97** [comment]
@katie312 这个应该是D4LA原始数据中自带的，最好保留

**Comment by katie312** [comment]
> @katie312 这个应该是D4LA原始数据中自带的，最好保留

好的，我目前是在根据D4LA的数据结构来自定义自己的数据，自定义的话应该不需要添加？

**Comment by JulioZhao97** [comment]
@katie312 是的

**Comment by xxanswer** [comment]
D4LA数据集，image里图片少了好多？

**Comment by JulioZhao97** [comment]
@xxanswer 您好，请问您可以提供更多细节吗？据我所知下载的数据中图片并没有缺失
![image](https://github.com/user-attachments/assets/8a8e9b22-cd91-4916-a551-ac9973c6cc8e)

**Comment by xxanswer** [comment]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/da513f1d-0fdc-4253-89e0-de09c315577b" />
对比发现我解压后的缺少了好多😭，我再重新下载解压一次吧。感谢🙏
