### ISSUE TITLE
作者您好，为什么还要加载yolov8模型的

### ISSUE THREAD

**Issue by YYH211** [opendatalab/DocLayout-YOLO#75]
![image](https://github.com/user-attachments/assets/0f4caaaa-3fe7-4749-8b65-782044fe0105)

**Comment by JulioZhao97** [comment]
@YYH211 您好，您可以参考这个：https://github.com/opendatalab/DocLayout-YOLO/issues/69

**Comment by YYH211** [comment]
OK 感谢
