### ISSUE TITLE
模型有什么区别

### ISSUE THREAD

**Issue by lyc728** [opendatalab/DocLayout-YOLO#9]
你好 关于你给的模型https://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/blob/main/doclayout_yolo_docstructbench_imgsz1024.pt和https://huggingface.co/opendatalab/PDF-Extract-Kit-1.0/blob/main/models/Layout/YOLO/doclayout_yolo_ft.pt这两个模型有什么区别呢

**Comment by JulioZhao97** [comment]
您好，这两个是一样的，只有命名上的区别

**Comment by lyc728** [comment]
可视化看了下 发现很多发票检测都不好

**Comment by JulioZhao97** [comment]
您好，可以提供一些可视化的例子供分析用，感谢反馈

**Comment by lyc728** [comment]
网上有很多增值税发票吧，你们可以看下

**Comment by JulioZhao97** [comment]
好的，感谢反馈
